### ISSUE TITLE
Glyphs offset very badly on vertical axis

### ISSUE THREAD

**Issue by Alhadis** [Slevinski/signwriting_2010_fonts#2]
When I open [this](http://graphemica.com/scripts/signwriting) or [this page](http://graphemica.com/%F0%9D%A0%86), I'm left looking at this:

<img src="https://cloud.githubusercontent.com/assets/2346707/16714628/b98ea31a-470c-11e6-8b82-56f76399db94.png" width="280" alt="Figure 1" valign="middle" /> <img src="https://cloud.githubusercontent.com/assets/2346707/16714630/c9fc6c78-470c-11e6-9468-c05c4976503b.png" width="350" alt="Figure 2" valign="middle" />

As you can see from the URL bar, it's not an issue with the page's styling, either:

<img src="https://cloud.githubusercontent.com/assets/2346707/16714634/db296924-470c-11e6-9da8-97f24152a30a.png" width="437" alt="Figure 3" />
## Specs:
- **OS:** Mac OS X 10.9.5 (Mavericks)
- **Screen size:** 1440 × 900
- **Browser:** Chrome v51.0.2704.103

**Comment by Slevinski** [comment]
Thanks for the excellent write-up.  This is a known issue and unfortunately by design.  The SignWriting 2010 Fonts are primarily used in 2-dimension.  They are placed at specific coordinates.  The text flows down from the baseline, so I created all of the glyphs below the baseline.

We spotted the same issue on Wikipedia for the Sutton SignWriting Unicode Block.  We added formatting to center the glyphs in the table.
https://en.wikipedia.org/wiki/Sutton_SignWriting_(Unicode_block)

This issue is also apparent when you double-click a symbol and then right click to copy.
![signwritingbelowbasemenu](https://cloud.githubusercontent.com/assets/376945/16717023/867100ca-46d2-11e6-8110-4217272659c6.png)

For stability, the SignWriting 2010 Fonts will not change.  However, later this year I will be releasing the [Sutton SignWriting Fonts](http://slevinski.github.io/#signwriting-font-face-project).  The new Sutton SignWriting Fonts will write above the baseline (for the most part).  The font is created at the 30px size, but some symbols are larger and will fall below the baseline.

The Sutton SignWriting Fonts will use Plane 4 and will not use ligatures or private use area characters.  I will be discussing my [Unicode 10 proposal](http://slevinski.github.io/SignWriting_Character_Viewer/SignWriting_Character_Viewer_2.html#?ui=en&set=uni10) for the Sutton SignWriting symbols at the next UTC meeting.  The new fonts will be available later this year.
- [SignWriting in Unicode Next](http://www.slideshare.net/StephenSlevinski/signwriting-in-unicode-next)

The SignWriting 2010 Fonts only partially support the Unicode 8 design.  Last year, I reported my issues to the UTC: [SignWriting in Unicode 8 Issues](http://www.slideshare.net/StephenSlevinski/sign-writing-in-unicode-8-issues).  We had a good discussion, then I wrote: [Thanks to the UTC](http://www.slideshare.net/StephenSlevinski/thanks-to-the-utc).

-Steve
[SignPuddle.com](http://signpuddle.com)

**Comment by Slevinski** [comment]
@Alhadis, I just added a new font file called SuttonSignWriting8.ttf in the fonts directory of the signwriting_2010_fonts repo which supports the Unicode 8 specification with glyphs above the baseline rather than below.  FYI
